### PR TITLE
feat: stock managment

### PR DESCRIPTION
**Pull request by denis-gandel**

### CODE REVIEW

**Comment by aguirrekarina** [comment]
https://github.com/user-attachments/assets/1e6f35bc-2049-4b4e-b6e8-7d1b69b4460f

When I buy from one and the other, the same message appears on both that the payment was correct and in the same case, on both, it appears that the stock is out.

**Comment by aguirrekarina** [comment]
https://github.com/user-attachments/assets/aafa9f3c-237a-4550-ae21-db827a0324da

Cart items are not deleted after a purchase.

**Review by daniel-espinoza-79 — COMMENTED** [review]
[Screencast from 2024-12-04 12-59-19.webm](https://github.com/user-attachments/assets/ff055953-068f-41a9-9150-49b8e92791bd)

Success Message is still being displayed when the stock is 0

**Comment by denis-gandel** [comment]
> Screencast.from.2024-12-04.12-59-19.webm 
> Success Message is still being displayed when the stock is 0

The message will appear whenever a product is out of stock, remember that STRIPE is the one that manages the payment process and not the application, so it will always send you that the payment was successful, because STRIPE does not manage the stock of the app, plus the application no longer works within the payment process, so if the stock of the product runs out for some reason X then you will still send as completed payment.

**Review by daniel-espinoza-79 — APPROVED** [review]

**Review by aguirrekarina — APPROVED** [review]

**Pull request merged**
