### PR TITLE
feat: shopping cart

### PR DESCRIPTION
**Pull request by denis-gandel**

### CODE REVIEW

**Review by daniel-espinoza-79 — COMMENTED** [review]
Screenshot from 2024-11-25 09-58-21


The product price in the cart is displayed with too many decimals (39.98999999999995); it is recommended to round it to two decimal places for better readability


you can replicate this adding products with .99 price

**Review by daniel-espinoza-79 — COMMENTED** [review]
Screenshot from 2024-11-25 10-00-51



UI should be customized to handle multiple attributes

**Comment by JorgeHB69** [comment]
image
The cart only shows the base price but not the total based on the quantity selected.

In the image case, I select five items (5 * 899.99 = 4499.95)

**Comment by JorgeHB69** [comment]
Based on the acceptance criteria:
`There should be a button to go to checkout if the user is logged in the button should just print something, but if not logged in it should send you to the login page showing a message with react notification or toast that you need to log in first to access shopping functions.`

But the checkout button not make redirection to "login" page for not logged users.

**Comment by JorgeHB69** [comment]
If the product variant has a price adjustment, it should be shown dynamically.
image
(On the image the price adjustment for this variant is "+100 /$" so the total price should be 899.99 /$)

It looks like the adjustment happens after each reset of the quantity information.

https://github.com/user-attachments/assets/a642d437-a024-4433-a183-091b16c49c65

**Comment by JorgeHB69** [comment]
For already logged users, still redirection to login

https://github.com/user-attachments/assets/eef8c146-665b-46cb-8610-a853f4efd51c

**Review by JorgeHB69 — APPROVED** [review]

**Review by denis-gandel — COMMENTED** [review]
There are changes that are already fixed within the branch, you are making existing changes.

**Pull request merged**
